title: "Xinyuan Lyu's Personal Website"
description: "Welcome to my personal websiteï¼"
theme: minima
baseurl: ""
url: "https://xinyuanlyu.github.io"


header_pages:
  - index.md
  - research.md
  - cv.md
  - portfolio.md
  - contact.md
