title: "Xinyuan Lyu's Personal Website"
description: "Welcome to my personal websiteÔºÅ"
theme: minima
baseurl: ""
url: "https://xinyuanlyu.github.io"


header_pages:
  - index.md
  - research.md
  - research-assistant-experience.md
  - portfolio.md 
  - Transcript.md
  - cv.md
  - personal-thoughts.md
  - my-poem.md
  - contact.md
